name: Build and deploy ASP.NET Core app to Azure Web App - turntablecharts-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Presentation/Presentation.csproj

      - name: Build
        run: dotnet build Presentation/Presentation.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Presentation/Presentation.csproj -c Release -o publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'turntablecharts-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9EB3831E78144859B7450DE2E9CA49F9 }}
